{{- range $name, $externalSecret := .Values.externalSecrets }}
{{- if include "common.hasApi" (list "external-secrets.io/v1/ExternalSecret" $) }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ $name }}
  labels:
    {{- include "app-extensions.labels" $ | nindent 4 }}
  {{- with $externalSecret.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  refreshInterval: {{ $externalSecret.refreshInterval | default "1h" }}
  secretStoreRef:
    name: {{ $externalSecret.secretStoreRef.name }}
    kind: {{ $externalSecret.secretStoreRef.kind | default "SecretStore" }}
  target:
    name: {{ $externalSecret.target.name | default $name }}
    creationPolicy: {{ $externalSecret.target.creationPolicy | default "Owner" }}
    {{- if $externalSecret.target.template }}
    template:
      {{- toYaml $externalSecret.target.template | nindent 6 }}
    {{- end }}
  {{- if $externalSecret.data }}
  data:
    {{- range $externalSecret.data }}
    - secretKey: {{ .secretKey }}
      remoteRef:
        key: {{ .remoteRef.key }}
        {{- if .remoteRef.property }}
        property: {{ .remoteRef.property }}
        {{- end }}
    {{- end }}
  {{- end }}
  {{- if $externalSecret.dataFrom }}
  dataFrom:
    {{- range $externalSecret.dataFrom }}
    - extract:
        key: {{ .extract.key }}
        {{- if .extract.property }}
        property: {{ .extract.property }}
        {{- end }}
    {{- end }}
  {{- end }}
{{- end }}
{{- end }}
