{{- range $name, $sealedSecret := .Values.sealedSecrets }}
{{- if include "common.hasApi" (list "bitnami.com/v1alpha1/SealedSecret" $) }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ $name }}
  labels:
    {{- include "app-extensions.labels" $ | nindent 4 }}
  {{- with $sealedSecret.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  encryptedData:
    {{- range $key, $value := $sealedSecret.encryptedData }}
    {{ $key }}: {{ $value }}
    {{- end }}
  template:
    metadata:
      name: {{ $sealedSecret.template.metadata.name | default $name }}
      {{- if $sealedSecret.template.metadata.labels }}
      labels:
        {{- toYaml $sealedSecret.template.metadata.labels | nindent 8 }}
      {{- end }}
      {{- if $sealedSecret.template.metadata.annotations }}
      annotations:
        {{- toYaml $sealedSecret.template.metadata.annotations | nindent 8 }}
      {{- end }}
    type: {{ $sealedSecret.template.type | default "Opaque" }}
{{- end }}
{{- end }}
