{{- range $name, $store := .Values.secretStores }}
{{- if include "common.hasApi" (list "external-secrets.io/v1/SecretStore" $) }}
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ $name }}
  labels:
    {{- include "app-extensions.labels" $ | nindent 4 }}
  {{- with $store.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  provider:
    {{- toYaml $store.provider | nindent 4 }}
{{- end }}
{{- end }}
