{{- if .Values.secrets }}
{{- range $name, $secret := .Values.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
  labels:
    {{- include "app-extensions.labels" $ | nindent 4 }}
  {{- with $secret.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: {{ $secret.type | default "Opaque" }}
{{- if $secret.data }}
data:
  {{- range $key, $value := $secret.data }}
  {{ $key }}: {{ tpl ($value | toString) $ | b64enc | quote }}
  {{- end }}
{{- end }}
{{- if $secret.stringData }}
stringData:
  {{- range $key, $value := $secret.stringData }}
  {{ $key }}: {{ tpl ($value | toString) $ | quote }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
