{{- if .Values.serviceAccounts }}
{{- range $name, $sa := .Values.serviceAccounts }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $name }}
  labels:
    {{- include "app-extensions.labels" $ | nindent 4 }}
  {{- with $sa.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- if $sa.imagePullSecrets }}
imagePullSecrets:
  {{- range $sa.imagePullSecrets }}
  - name: {{ . }}
  {{- end }}
{{- end }}
{{- if $sa.secrets }}
secrets:
  {{- range $sa.secrets }}
  - name: {{ . }}
  {{- end }}
{{- end }}
automountServiceAccountToken: {{ $sa.automountServiceAccountToken | default true }}
{{- end }}
{{- end }}
