apiVersion: v2
name: platform-extensions
description: Cluster-scoped Kubernetes resources for platform teams (requires cluster-admin)
type: application
version: 1.5.0
appVersion: "1.0.0"
kubeVersion: ">=1.22.0-0"
home: https://github.com/synkube/
sources:
  - https://github.com/synkube/charts/tree/main/charts/platform-extensions
icon: https://raw.githubusercontent.com/synkube/.github/main/assets/synkube-logo-256.jpg
keywords:
  - platform
  - extensions
  - one-chart-to-extend-them-all
  - cluster-resources
  - external-secrets
  - sealed-secrets
  - cert-manager
  - cluster-issuer
  - certificates
  - networking
  - rbac
  - webhooks
  - admission-control
  - leader-election
  - volume-snapshots
  - scheduled-snapshots
  - backup
  - universal
maintainers:
  - name: bsgrigorov
annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/category: integration-delivery
dependencies:
  - name: common
    version: "1.0.0"
    repository: "file://../common"
