{{- range $name, $store := .Values.clusterSecretStores }}
{{- if include "common.hasApi" (list "external-secrets.io/v1/ClusterSecretStore" $) }}
---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: {{ $name }}
  labels:
    {{- include "platform-extensions.labels" $ | nindent 4 }}
  {{- with $store.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  provider:
    {{- toYaml $store.provider | nindent 4 }}
  {{- if $store.conditions }}
  conditions:
    {{- toYaml $store.conditions | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
