{{- range $name, $externalSecret := .Values.externalSecrets }}
{{- if include "common.hasApi" (list "external-secrets.io/v1/ExternalSecret" $) }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ $name }}
  {{- with $externalSecret.namespace }}
  namespace: {{ . }}
  {{- end }}
  labels:
    {{- include "platform-extensions.labels" $ | nindent 4 }}
  {{- with $externalSecret.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  refreshInterval: {{ $externalSecret.refreshInterval | default "1h" }}
  secretStoreRef:
    name: {{ $externalSecret.secretStoreRef.name }}
    kind: {{ $externalSecret.secretStoreRef.kind | default "ClusterSecretStore" }}
  target:
    name: {{ $externalSecret.target.name | default $name }}
    creationPolicy: {{ $externalSecret.target.creationPolicy | default "Owner" }}
    {{- with $externalSecret.target.deletionPolicy }}
    deletionPolicy: {{ . }}
    {{- end }}
    {{- if $externalSecret.target.template }}
    template:
      {{- toYaml $externalSecret.target.template | nindent 6 }}
    {{- end }}
  {{- if $externalSecret.data }}
  data:
    {{- range $externalSecret.data }}
    - secretKey: {{ .secretKey }}
      remoteRef:
        key: {{ .remoteRef.key }}
        {{- if .remoteRef.property }}
        property: {{ .remoteRef.property }}
        {{- end }}
        {{- if .remoteRef.version }}
        version: {{ .remoteRef.version }}
        {{- end }}
        {{- if .remoteRef.conversionStrategy }}
        conversionStrategy: {{ .remoteRef.conversionStrategy }}
        {{- end }}
        {{- if .remoteRef.decodingStrategy }}
        decodingStrategy: {{ .remoteRef.decodingStrategy }}
        {{- end }}
    {{- end }}
  {{- end }}
  {{- if $externalSecret.dataFrom }}
  dataFrom:
    {{- range $externalSecret.dataFrom }}
    - extract:
        key: {{ .extract.key }}
        {{- if .extract.property }}
        property: {{ .extract.property }}
        {{- end }}
        {{- if .extract.version }}
        version: {{ .extract.version }}
        {{- end }}
        {{- if .extract.conversionStrategy }}
        conversionStrategy: {{ .extract.conversionStrategy }}
        {{- end }}
        {{- if .extract.decodingStrategy }}
        decodingStrategy: {{ .extract.decodingStrategy }}
        {{- end }}
      {{- if .rewrite }}
      rewrite:
        {{- range .rewrite }}
        - regexp:
            source: {{ .regexp.source }}
            target: {{ .regexp.target }}
        {{- end }}
      {{- end }}
    {{- end }}
  {{- end }}
{{- end }}
{{- end }}
