{{- if .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app-starter.fullname" . }}
  labels:
{{ include "app-starter.labels" . | indent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ tpl ($value | toString) $ | b64enc | quote }}
  {{- end }}
{{- end }}
