{{- if .Values.service.enabled -}}
{{- $fullName := include "app-starter.fullname" . -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "app-starter.fullname" . }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
{{ include "app-starter.labels" . | indent 4 }}
  {{- with .Values.service.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.service.headless }}
  clusterIP: None
  {{- end }}
  ports:
    {{- range .Values.service.ports }}
    - port: {{ .port }}
      targetPort: {{ .targetPort | default .port }}
      protocol: {{ .protocol | default "TCP" }}
      name: {{ .name }}
    {{- end }}
  selector:
    {{- include "app-starter.selectorLabels" . | nindent 4 }}
{{- end -}}
