{{- if and .Values.vpa.enabled (include "common.hasApi" (list "autoscaling.k8s.io/v1beta2/VerticalPodAutoscaler" .)) }}
apiVersion: autoscaling.k8s.io/v1beta2
kind: VerticalPodAutoscaler
metadata:
  name: {{ include "app-starter.fullname" . }}
  labels:
{{ include "app-starter.labels" . | indent 4 }}
spec:
  targetRef:
    apiVersion: "apps/v1"
    {{- if .Values.statefulSet.enabled }}
    kind: StatefulSet
    {{- else }}
    kind: Deployment
    {{- end }}
    name: {{ include "app-starter.fullname" . }}
  updatePolicy:
    updateMode: "Off"
{{- else if and .Values.vpa.enabled (not (include "common.hasApi" (list "autoscaling.k8s.io/v1beta2/VerticalPodAutoscaler" .))) }}
# Warning: VerticalPodAutoscaler CRD not available in this cluster
# Install VPA to use VerticalPodAutoscaler resources
# https://github.com/kubernetes/autoscaler/tree/master/vertical-pod-autoscaler
{{- end }}
