apiVersion: v2
name: app-extensions
description: Namespace-scoped Kubernetes resources for application teams
type: application
version: 1.2.0
appVersion: "1.0.0"
kubeVersion: ">=1.22.0-0"
home: https://github.com/synkube/charts
sources:
  - https://github.com/synkube/charts
icon: https://raw.githubusercontent.com/synkube/.github/main/assets/synkube-logo-256.jpg
keywords:
  - extensions
  - one-chart-to-extend-them-all
  - networking
  - rbac
  - universal
  - secrets
  - configmaps
  - serviceaccounts
maintainers:
  - name: bsgrigorov
annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/category: integration-delivery
  artifacthub.io/links: |
    - name: Source
      url: https://github.com/synkube/charts/tree/main/charts/app-extensions
    - name: Homepage
      url: https://github.com/synkube/
dependencies:
  - name: common
    version: "1.0.0"
    repository: "file://../common"
