apiVersion: v2
name: app-starter
description: A streamlined, extensible Helm chart for deploying applications on Kubernetes
type: application
version: 1.0.0
appVersion: "1.0.0"
kubeVersion: ">=1.22.0-0"
home: https://github.com/synkube/synkube-charts
sources:
  - https://github.com/synkube/synkube-charts
icon: https://raw.githubusercontent.com/synkube/.github/main/assets/synkube-logo-256.jpg
keywords:
  - app-starter
  - extensible
  - one-chart-to-rule-them-all
  - generic-app
  - deployment
  - statefulset
  - cronjob
  - ingress
  - universal
  - boilerplate
  - workloads
  - autoscaling
  - gateway-api
maintainers:
  - name: bsgrigorov
annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/category: integration-delivery

dependencies:
  - name: common
    version: "1.0.0"
    repository: "file://../common"
